package com.infinity.omos.ui.onboarding

enum class ErrorMessage {
    DEFAULT,
    NO_ERROR,
    INCORRECT_CONTENTS_ERROR_MESSAGE,
    BLANK_EMAIL_ERROR_MESSAGE,
    BLANK_PASSWORD_ERROR_MESSAGE,
    NOT_MATCH_PASSWORD_ERROR_MESSAGE,
    NOT_MATCH_CONFIRM_PASSWORD_ERROR_MESSAGE,
    NOT_EXIST_USER_ERROR_MESSAGE,
    INCORRECT_AUTH_CODE_ERROR_MESSAGE,
    NETWORK_ERROR_MESSAGE,
    ALREADY_EXIST_NICKNAME_ERROR_MESSAGE,
    ALREADY_EXIST_EMAIL_ERROR_MESSAGE,
}