name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Secret Action (local.properties)
          env:
            OMOS_BASE_URL: ${{secrets.OMOS_BASE_URL}}
            KAKAO_NATIVE_APP_KEY: ${{secrets.KAKAO_NATIVE_APP_KEY}}
            KAKAO_OAUTH_KEY: ${{secrets.KAKAO_OAUTH_KEY}}
            S3_BASE_URL: ${{secrets.S3_BASE_URL}}
            RELEASE_STORE_FILE: ${{secrets.RELEASE_STORE_FILE}}
            RELEASE_STORE_PASSWORD: ${{secrets.RELEASE_STORE_PASSWORD}}
            RELEASE_KEY_ALIAS: ${{secrets.RELEASE_KEY_ALIAS}}
            RELEASE_KEY_PASSWORD: ${{secrets.RELEASE_KEY_PASSWORD}}
          run: |
            echo omos_base_url="$OMOS_BASE_URL" >> ./local.properties
            echo kakao_native_app_key="$KAKAO_NATIVE_APP_KEY" >> ./local.properties
            echo kakao_oauth_key="$KAKAO_OAUTH_KEY" >> ./local.properties
            echo s3_base_url="$S3_BASE_URL" >> ./local.properties
            echo RELEASE_STORE_FILE="$RELEASE_STORE_FILE" >> ./local.properties
            echo RELEASE_STORE_PASSWORD="$RELEASE_STORE_PASSWORD" >> ./local.properties
            echo RELEASE_KEY_ALIAS="$RELEASE_KEY_ALIAS" >> ./local.properties
            echo RELEASE_KEY_PASSWORD="$RELEASE_KEY_PASSWORD" >> ./local.properties

      - name: Generate Keystore file from Github Secrets
        env:
          BASE_64_KEYSTORE: ${{secrets.BASE_64_KEYSTORE}}
        run: |
          echo "$BASE_64_KEYSTORE" > ./app/keystore/keystore.b64
          base64 -d -i ./app/keystore/keystore.b64 > ./app/keystore/iamjmKey.jks

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Local Properties
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest