# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: OMOS-CD

on:
  push:
    branches:
      - dist
  pull_request:
    branches:
      - dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk

      - name: Decode Secret Action (local.properties)
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          KAKAO_NATIVE_APP_KEY: ${{secrets.KAKAO_NATIVE_APP_KEY}}
          KAKAO_OAUTH_KEY: ${{secrets.KAKAO_OAUTH_KEY}}
          IAM_ACCESS_KEY: ${{secrets.IAM_ACCESS_KEY}}
          IAM_SECRET_KEY: ${{secrets.IAM_SECRET_KEY}}
          S3_BASE_URL: ${{secrets.S3_BASE_URL}}
          RELEASE_STORE_FILE: ${{secrets.RELEASE_STORE_FILE}}
          RELEASE_STORE_PASSWORD: ${{secrets.RELEASE_STORE_PASSWORD}}
          RELEASE_KEY_ALIAS: ${{secrets.RELEASE_KEY_ALIAS}}
          RELEASE_KEY_PASSWORD: ${{secrets.RELEASE_KEY_PASSWORD}}
        run: |
          echo base_url="$BASE_URL" >> ./local.properties
          echo kakao_native_app_key="$KAKAO_NATIVE_APP_KEY" >> ./local.properties
          echo kakao_oauth_key="$KAKAO_OAUTH_KEY" >> ./local.properties
          echo iam_access_key="$IAM_ACCESS_KEY" >> ./local.properties
          echo iam_secret_key="$IAM_SECRET_KEY" >> ./local.properties
          echo s3_base_url="$S3_BASE_URL" >> ./local.properties
          echo RELEASE_STORE_FILE="$RELEASE_STORE_FILE" >> ./local.properties
          echo RELEASE_STORE_PASSWORD="$RELEASE_STORE_PASSWORD" >> ./local.properties
          echo RELEASE_KEY_ALIAS="$RELEASE_KEY_ALIAS" >> ./local.properties
          echo RELEASE_KEY_PASSWORD="$RELEASE_KEY_PASSWORD" >> ./local.properties

      - name: Generate Keystore file from Github Secrets
        env:
          BASE_64_KEYSTORE: ${{secrets.BASE_64_KEYSTORE}}
        run: |
          echo "$BASE_64_KEYSTORE" > ./app/keystore/keystore.b64
          base64 -d -i ./app/keystore/keystore.b64 > ./app/keystore/jaeminKey.jks

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --warning-mode all --stacktrace

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Build APK
        run: bash ./gradlew assembleRelease --warning-mode all --stacktrace

      - run: './gradlew assembleRelease'
      - uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL_DEPLOY }}
          file_path: 'app/build/outputs/apk/release/app-release.apk'
          file_name: 'app-release.apk'
          file_type: 'apk'
          initial_comment: 'OMOS 최신 빌드 앱 배포(Android) - ${{github.event.head_commit.message}}'

      - name: apk upload
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/release/app-release.apk
